eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/
server:
  port: 8022
spring:
  cloud:
    inetutils:
      timeout-seconds: 100
  application:
    name: service-zuul
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
zuul:
  routes:
    config:
      path: /config/**
      serviceId: config-server
    business:
      path: /business/**
      serviceId: business
    business-consumer:
      path: /business-consumer/**
      serviceId: business-consumer
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

##项目信息
info:
  name: ${spring.application.name}
  server:
    port: ${server.port}