server:
  port: 8020
spring:
  application:
    name: netflix-eureka-server
    instance_id: eureka
eureka:
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #server:
    #enable-self-preservation: false   #Eureka服务端关闭心跳连接测试